version: 2
updates:
  # Maintain dependencies for the core library
  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    target-branch: "main"
    directories:
      - "/ghcr.io/flutterint/*"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
