---
name: Build & Publish Docker Images
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
      continue: ${{ steps.generate-matrix.outputs.continue }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate matrix
        id: generate-matrix
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            BASE_SHA="HEAD~1"
          else
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
          fi
          CHANGED_DIRS=$(git diff --name-only $BASE_SHA | xargs -I {} dirname {} | cut -d'/' -f1-3 | grep -v .git | grep '/' | sort -u)
          MATRIX_PROJECTS_JSON="["
          MATRIX_INCLUDE_JSON="["
          for DIR in ${CHANGED_DIRS}; do
            MATRIX_PROJECTS_JSON+=$(sed 's/^/"/;s/$/"/' <<< "${DIR}")
            DOCKERFILE="${DIR}/Dockerfile"
            MATRIX_INCLUDE_JSON+="{\"project\": \"${DIR}\", \"dockerfile\": \"${DOCKERFILE}\"}"
          done

          MATRIX_INCLUDE_JSON="${MATRIX_INCLUDE_JSON//\}\{/\}, \{}"
          MATRIX_INCLUDE_JSON+="]"
          MATRIX_PROJECTS_JSON="${MATRIX_PROJECTS_JSON//\"\"/\", \"}"
          MATRIX_PROJECTS_JSON+="]"
          MATRIX_JSON="{\"projects\": ${MATRIX_PROJECTS_JSON}, \"include\": ${MATRIX_INCLUDE_JSON}}"
          echo "${MATRIX_JSON}"
          CONTINUE_DOCKER_JOB="no"
          if [[ "${MATRIX_PROJECTS_JSON}" != "[]" ]]; then
            CONTINUE_DOCKER_JOB="yes"
          fi
          echo "continue=${CONTINUE_DOCKER_JOB}" >> $GITHUB_OUTPUT
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    if: needs.setup.outputs.continue == 'yes'
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build -t ${{ matrix.project }}:latest ${{ matrix.project }}
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
      - name: Run terratest
        run: go test ./${{ matrix.project }}/test
      - name: Push the Docker image
        run: docker push ${{ matrix.project }}:latest
        if: github.event_name != 'pull_request'
